In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [11]:
df1= pd.read_csv('prices_round_0_day_-1.csv',delimiter=';')

In [12]:
df1

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,-1,0,TOMATOES,4999,5,4998,15,NaN,NaN,5013,5,5014,15,NaN,NaN,5006.0,0.0
1,-1,0,EMERALDS,9992,14,9990,29,NaN,NaN,10008,14,10010,29,NaN,NaN,10000.0,0.0
2,-1,100,EMERALDS,9992,11,9990,22,NaN,NaN,10008,11,10010,22,NaN,NaN,10000.0,0.0
3,-1,100,TOMATOES,5000,8,4998,21,NaN,NaN,5013,8,5014,21,NaN,NaN,5006.5,0.0
4,-1,200,EMERALDS,9992,15,9990,20,NaN,NaN,10008,15,10010,20,NaN,NaN,10000.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,-1,999700,EMERALDS,9992,12,9990,26,NaN,NaN,10008,12,10010,26,NaN,NaN,10000.0,0.0
19996,-1,999800,EMERALDS,9992,13,9990,20,NaN,NaN,10008,13,10010,20,NaN,NaN,10000.0,0.0
19997,-1,999800,TOMATOES,4951,6,4949,18,NaN,NaN,4964,6,4965,18,NaN,NaN,4957.5,0.0
19998,-1,999900,TOMATOES,4950,10,4949,25,NaN,NaN,4964,10,4965,25,NaN,NaN,4957.0,0.0
19999,-1,999900,EMERALDS,9992,10,9990,29,NaN,NaN,10008,10,10010,29,NaN,NaN,10000.0,0.0

In [13]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   day              20000 non-null  int64
 1   timestamp        20000 non-null  int64
 2   product          20000 non-null  object
 3   bid_price_1      20000 non-null  int64
 4   bid_volume_1     20000 non-null  int64
 5   bid_price_2      20000 non-null  int64
 6   bid_volume_2     20000 non-null  int64
 7   bid_price_3      525 non-null    float64
 8   bid_volume_3     525 non-null    float64
 9   ask_price_1      20000 non-null  int64
 10  ask_volume_1     20000 non-null  int64
 11  ask_price_2      20000 non-null  int64
 12  ask_volume_2     20000 non-null  int64
 13  ask_price_3      518 non-null    float64
 14  ask_volume_3     518 non-null    float64
 15  mid_price        20000 non-null  float64
 16  profit_and_loss  20000 non-null  float64
dtypes: float64(6), int64(10), object(1)
memory usage: 2.6+ MB

In [16]:
df2=pd.read_csv('prices_round_0_day_-2.csv',delimiter=';')

In [17]:
df2

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,-2,0,EMERALDS,9992,11,9990,25,NaN,NaN,10008,11,10010,25,NaN,NaN,10000.0,0.0
1,-2,0,TOMATOES,4993,7,4992,17,NaN,NaN,5007,7,5008,17,NaN,NaN,5000.0,0.0
2,-2,100,TOMATOES,4998,5,4993,7,4992.0,16.0,5007,7,5008,16,NaN,NaN,5002.5,0.0
3,-2,100,EMERALDS,9992,15,9990,20,NaN,NaN,10008,15,10010,20,NaN,NaN,10000.0,0.0
4,-2,200,TOMATOES,4994,6,4993,20,NaN,NaN,5008,6,5009,20,NaN,NaN,5001.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,-2,999700,EMERALDS,9992,10,9990,22,NaN,NaN,10008,10,10010,22,NaN,NaN,10000.0,0.0
19996,-2,999800,EMERALDS,9992,14,9990,25,NaN,NaN,10008,14,10010,25,NaN,NaN,10000.0,0.0
19997,-2,999800,TOMATOES,5000,7,4999,24,NaN,NaN,5014,7,5015,24,NaN,NaN,5007.0,0.0
19998,-2,999900,TOMATOES,5000,7,4998,20,NaN,NaN,5013,7,5015,20,NaN,NaN,5006.5,0.0
19999,-2,999900,EMERALDS,9992,13,9990,30,NaN,NaN,10008,13,10010,30,NaN,NaN,10000.0,0.0

In [20]:
df3= pd.read_csv('trades_round_0_day_-1.csv',delimiter=';')

In [21]:
df3

     timestamp  buyer  seller    symbol currency    price  quantity
0         3200    NaN     NaN  EMERALDS   XIRECS   9992.0         8
1         3400    NaN     NaN  TOMATOES   XIRECS   5009.0         2
2         5000    NaN     NaN  EMERALDS   XIRECS   9992.0         7
3         7000    NaN     NaN  TOMATOES   XIRECS   5010.0         4
4         9600    NaN     NaN  TOMATOES   XIRECS   4999.0         5
..         ...    ...     ...       ...      ...      ...       ...
626     983800    NaN     NaN  EMERALDS   XIRECS  10008.0         3
627     985100    NaN     NaN  TOMATOES   XIRECS   4946.0         2
628     985600    NaN     NaN  EMERALDS   XIRECS  10008.0         6
629     993000    NaN     NaN  TOMATOES   XIRECS   4956.0         2
630     995600    NaN     NaN  TOMATOES   XIRECS   4958.0         3

[631 rows x 7 columns]

In [22]:
df4=pd.read_csv('trades_round_0_day_-2.csv',delimiter=';')

In [23]:
df4

     timestamp  buyer  seller    symbol currency    price  quantity
0          900    NaN     NaN  TOMATOES   XIRECS   5008.0         2
1         1700    NaN     NaN  TOMATOES   XIRECS   5006.0         3
2         4000    NaN     NaN  EMERALDS   XIRECS  10008.0         7
3         4100    NaN     NaN  TOMATOES   XIRECS   5002.0         3
4         5200    NaN     NaN  EMERALDS   XIRECS   9992.0         5
..         ...    ...     ...       ...      ...      ...       ...
583     986100    NaN     NaN  TOMATOES   XIRECS   5002.0         5
584     988600    NaN     NaN  TOMATOES   XIRECS   5004.0         5
585     989300    NaN     NaN  TOMATOES   XIRECS   5017.0         2
586     991500    NaN     NaN  TOMATOES   XIRECS   5017.0         2
587     991700    NaN     NaN  TOMATOES   XIRECS   5004.0         4

[588 rows x 7 columns]